# Generated by Django 4.2 on 2025-07-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
