# Generated by Django 4.2 on 2025-07-18 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_subscription_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('science', 'Science'), ('sports', 'Sports'), ('technology', 'Technology')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 18, 16, 7, 0, 449303)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('chat_id', 'category')},
        ),
    ]
