# Generated by Django 4.2 on 2025-07-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_subscription_category_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('sports', 'Sports'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('science', 'Science')], default='general', max_length=20),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
    ]
